# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Enhanced 
tagline:          'A place for the things'
description:      'All of my various projects from OSS to radio and machining / gun making can be found here"
url:              http://enhanced.github.io
baseurl:          /

author:
  name:           'JJ Cummings'
  url:            https://twitter.com/enhancedx

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/enhanced/enhanced.github.io
